### ISSUE TITLE
[BUG] Trello URL not working

### ISSUE THREAD

**Issue by chris400** [SDCore/Apex-Stats-Bot#23]
**Describe the bug**
The URL to the Trello board is not found

**To Reproduce**
1. Go to https://apexstats.dev/trello
~2. Click on '....'~
~3. Scroll down to '....'~

**Expected behavior**
The Trello board should be show

**Screenshots**
![image](https://user-images.githubusercontent.com/10909668/115767097-072b2280-a3a9-11eb-9fa8-dd533b431e95.png)

**Comment by SDCore** [comment]
Thanks! Pushed an update to the site, should be working shortly
